/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "DB": {
      "databaseId": string
      "type": "sst.cloudflare.D1"
    }
    "RecipeExtraction": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "Scraper": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "StaticSite": {
      "type": "sst.cloudflare.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}