/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRecipeRouteImport } from './routes/new-recipe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesRecipeSlugRouteImport } from './routes/recipes.$recipeSlug'

const NewRecipeRoute = NewRecipeRouteImport.update({
  id: '/new-recipe',
  path: '/new-recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeSlugRoute = RecipesRecipeSlugRouteImport.update({
  id: '/recipes/$recipeSlug',
  path: '/recipes/$recipeSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-recipe': typeof NewRecipeRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-recipe': typeof NewRecipeRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/new-recipe': typeof NewRecipeRoute
  '/recipes/$recipeSlug': typeof RecipesRecipeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/new-recipe' | '/recipes/$recipeSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/new-recipe' | '/recipes/$recipeSlug'
  id: '__root__' | '/' | '/login' | '/new-recipe' | '/recipes/$recipeSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NewRecipeRoute: typeof NewRecipeRoute
  RecipesRecipeSlugRoute: typeof RecipesRecipeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new-recipe': {
      id: '/new-recipe'
      path: '/new-recipe'
      fullPath: '/new-recipe'
      preLoaderRoute: typeof NewRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeSlug': {
      id: '/recipes/$recipeSlug'
      path: '/recipes/$recipeSlug'
      fullPath: '/recipes/$recipeSlug'
      preLoaderRoute: typeof RecipesRecipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NewRecipeRoute: NewRecipeRoute,
  RecipesRecipeSlugRoute: RecipesRecipeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
